/ekf_node:
  ros__parameters:
    # --- Modalità Esecuzione ---
    use_sim_perception: true    # Se TRUE usa pacsim::msg, se FALSE usa MarkerArray (Real/Rosbag)

    # --- Configurazione Topic (Attuali PacSim) ---
    imu_topic: "/pacsim/imu/cog_imu"
    perception_topic: "/pacsim/perception/livox_front/landmarks"
    perception_topic_real: "/perception/cones"
    odom_topic: "/ekf/odometry"
    pose_topic: "/ekf_pose_only"
    map_topic: "/ekf/map_cones"

    # --- Tuning "Aggressivo" (Forza la correzione) ---
    process_noise_x: 0.001
    process_noise_y: 0.001      
    process_noise_yaw: 0.01
    process_noise_v: 0.1
    process_noise_vy: 0.2
    process_noise_omega: 0.3
    
    lidar_noise_x: 0.05
    lidar_noise_y: 0.05
    
    association_threshold: 9.21
    max_distance: 15.0

    # Calibrazione
    imu_yaw_offset: 0.0