/ekf_node:
  ros__parameters:
    max_dt: 1.0
    
    # --- Tuning "Aggressivo" (Forza la correzione) ---
    
    # AUMENTA questi valori. Di al robot che le ruote scivolano!
    # Questo aumenta la Matrice P (Incertezza posizione)
    process_noise_v: 0.05
    process_noise_vy: 0.05      # Prova 2.5 o 3.0 (era 0.8) -> 0.5 per la simulazione
    process_noise_omega: 0.005   # Prova 2.5 o 3.0 (era 0.5) -> come sopra
    
    # RILASSA leggermente questi valori
    # Se sono troppo piccoli, rischi di scartare dati validi
    meas_noise_range: 0.062     # 10 cm è più realistico di 5 cm
    meas_noise_bearing: 0.015    # Va bene
    
    # IMPORTANTE: Data Association
    association_threshold: 3.9 # 50.0 è ENORME! -> 5 per la simulazion
